language: cpp

install:
  - cd Software
  - make
  - ls -al 
  - ./main
script:
  - arduino --verify --board arduino:avr:nano:cpu=atmega168 $PWD/Software/TelescopeController.ino
notifications:
  email:
    on_success: change
    on_failure: change
